include("${CMAKE_CURRENT_LIST_DIR}/Common.cmake")

set(CMAKE_MAKE_PROGRAM "${TOOLCHAIN_NINJA}" CACHE FILEPATH "The local Ninja executable." FORCE)
set(LLVM_PARALLEL_LINK_JOBS 1 CACHE STRING "Native generator links share one slot." FORCE)
set(CMAKE_BUILD_TYPE Release CACHE STRING "The build tools use optimization without debug information." FORCE)
set(CMAKE_C_COMPILER "${TOOLCHAIN_CLANG}" CACHE FILEPATH "Xcode supplies the bootstrap C compiler." FORCE)
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_CLANGXX}" CACHE FILEPATH "Xcode supplies the bootstrap C++ compiler." FORCE)
set(CMAKE_OSX_SYSROOT macosx CACHE STRING "TableGen runs on the build machine." FORCE)
set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "The build machine uses Apple silicon." FORCE)
set(LLVM_ENABLE_PROJECTS clang CACHE STRING "Clang supplies its TableGen executable." FORCE)
set(LLVM_TARGETS_TO_BUILD WebAssembly CACHE STRING "The final compiler needs the WebAssembly backend." FORCE)
set(LLVM_INCLUDE_TESTS OFF CACHE BOOL "Only the two generator tools are selected." FORCE)
set(LLVM_INCLUDE_BENCHMARKS OFF CACHE BOOL "Benchmarks are outside this build." FORCE)
set(LLVM_INCLUDE_EXAMPLES OFF CACHE BOOL "Examples are outside this build." FORCE)
set(LLVM_INCLUDE_DOCS OFF CACHE BOOL "Documentation is outside this build." FORCE)
set(CLANG_INCLUDE_TESTS OFF CACHE BOOL "Clang tests are outside the generator build." FORCE)
set(LLVM_ENABLE_ZSTD OFF CACHE BOOL "The profile needs no compressed debug sections." FORCE)
set(LLVM_APPEND_VC_REV OFF CACHE BOOL "Archive inputs use manifest provenance instead of a parent Git checkout." FORCE)
