include("${CMAKE_CURRENT_LIST_DIR}/Common.cmake")

set(CMAKE_MAKE_PROGRAM "${TOOLCHAIN_NINJA}" CACHE FILEPATH "The local Ninja executable." FORCE)
set(CMAKE_BUILD_TYPE Release CACHE STRING "The libraries use optimization without debug information." FORCE)
set(LLVM_PARALLEL_LINK_JOBS 1 CACHE STRING "Archive and executable links share one build slot." FORCE)
set(CMAKE_SYSTEM_NAME iOS CACHE STRING "LLVM support libraries execute inside the iOS host." FORCE)
set(CMAKE_OSX_SYSROOT iphoneos CACHE STRING "LLVM support libraries use the device SDK." FORCE)
set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "The compiler host uses arm64." FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET ${TOOLCHAIN_DEPLOYMENT_TARGET} CACHE STRING "Native compiler libraries use the supported deployment floor." FORCE)
set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE CACHE STRING "Link probes validate iOS SDK libraries without running their outputs." FORCE)
set(CMAKE_MACOSX_BUNDLE OFF CACHE BOOL "Only library targets are selected." FORCE)
set(LLVM_ENABLE_PROJECTS "clang;lld" CACHE STRING "Swift needs Clang libraries and the WebAssembly linker." FORCE)
set(LLVM_TARGETS_TO_BUILD WebAssembly CACHE STRING "Only WebAssembly code generation is needed." FORCE)
set(LLVM_DEFAULT_TARGET_TRIPLE ${TOOLCHAIN_PROGRAM_TARGET} CACHE STRING "The compiler emits WASM programs." FORCE)
set(LLVM_HOST_TRIPLE ${TOOLCHAIN_COMPILER_HOST} CACHE STRING "The compiler itself runs on iOS." FORCE)
set(LLVM_NATIVE_TOOL_DIR "${TOOLCHAIN_BUILD_ROOT}/host-tools/bin" CACHE PATH "Generators run on the Mac." FORCE)
set(LLVM_INCLUDE_TESTS OFF CACHE BOOL "Only the selected library graph is configured." FORCE)
set(LLVM_INCLUDE_BENCHMARKS OFF CACHE BOOL "Benchmarks are outside this build." FORCE)
set(LLVM_INCLUDE_EXAMPLES OFF CACHE BOOL "Examples are outside this build." FORCE)
set(LLVM_INCLUDE_DOCS OFF CACHE BOOL "Documentation is outside this build." FORCE)
set(CLANG_INCLUDE_TESTS OFF CACHE BOOL "Clang tests are outside this library build." FORCE)
set(LLVM_ENABLE_ZSTD OFF CACHE BOOL "The profile needs no compressed debug sections." FORCE)
set(LLVM_ENABLE_LIBXML2 OFF CACHE BOOL "The profile does not need LLVM's optional XML tools." FORCE)
set(LLVM_ENABLE_LIBEDIT OFF CACHE BOOL "The profile has no terminal editor dependency." FORCE)
set(LLVM_APPEND_VC_REV OFF CACHE BOOL "Archive inputs use manifest provenance instead of a parent Git checkout." FORCE)
