include("${CMAKE_CURRENT_LIST_DIR}/Common.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/RestrictedNative.cmake")
if(NOT EXISTS "${TOOLCHAIN_BOOTSTRAP_ROOT}/bin/swiftc")
  message(FATAL_ERROR "Set TOOLCHAIN_BOOTSTRAP_ROOT to the matching Swift release usr directory.")
endif()

set(CMAKE_MAKE_PROGRAM "${TOOLCHAIN_NINJA}" CACHE FILEPATH "The local Ninja executable." FORCE)
set(CMAKE_BUILD_TYPE Release CACHE STRING "Native compiler libraries use an optimized build." FORCE)
set(SWIFT_PARALLEL_LINK_JOBS 1 CACHE STRING "Archive and executable links share one build slot." FORCE)
set(CMAKE_SYSTEM_NAME Darwin CACHE STRING "The platform family expected by Swift's build system." FORCE)
set(CMAKE_SYSTEM_PROCESSOR arm64 CACHE STRING "The compiler host architecture." FORCE)
set(CMAKE_OSX_SYSROOT iphoneos CACHE STRING "The native compiler uses the iOS SDK." FORCE)
set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "The native compiler has one device architecture." FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET ${TOOLCHAIN_DEPLOYMENT_TARGET} CACHE STRING "Native compiler libraries use the supported deployment floor." FORCE)
set(CMAKE_MACOSX_BUNDLE OFF CACHE BOOL "Only compiler libraries are selected." FORCE)
set(CMAKE_DISABLE_FIND_PACKAGE_LibEdit ON CACHE BOOL "The compiler profile has no terminal editor dependency." FORCE)
set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE CACHE STRING "Link probes validate iOS SDK libraries without running their outputs." FORCE)
set(CMAKE_Swift_COMPILER "${TOOLCHAIN_BOOTSTRAP_ROOT}/bin/swiftc" CACHE FILEPATH "The installed bootstrap compiler." FORCE)
set(CMAKE_Swift_COMPILER_TARGET ${TOOLCHAIN_COMPILER_HOST} CACHE STRING "Swift implementation code runs on iOS." FORCE)
set(CMAKE_Swift_NUM_THREADS 1 CACHE STRING "Ninja controls build parallelism across Swift modules." FORCE)
set(CMAKE_Swift_FLAGS "-target ${TOOLCHAIN_COMPILER_HOST} -module-cache-path \"${TOOLCHAIN_BUILD_ROOT}/swift-module-cache\" -file-prefix-map \"${TOOLCHAIN_SOURCE_ROOT}=/toolchain/sources\" -file-prefix-map \"${TOOLCHAIN_BUILD_ROOT}=/toolchain/build\" -file-prefix-map \"${TOOLCHAIN_REPOSITORY_ROOT}=/toolchain/producer\"" CACHE STRING "Native Swift source paths use stable prefixes." FORCE)

set(LLVM_DIR "${TOOLCHAIN_BUILD_ROOT}/llvm-ios/lib/cmake/llvm" CACHE PATH "The configured iOS LLVM libraries." FORCE)
set(Clang_DIR "${TOOLCHAIN_BUILD_ROOT}/llvm-ios/lib/cmake/clang" CACHE PATH "The configured iOS Clang libraries." FORCE)
set(LLVM_TABLEGEN "${TOOLCHAIN_BUILD_ROOT}/host-tools/bin/llvm-tblgen" CACHE FILEPATH "Table generation runs on macOS." FORCE)
set(SWIFT_NATIVE_LLVM_TOOLS_PATH "${TOOLCHAIN_BUILD_ROOT}/host-tools/bin" CACHE PATH "Build tools run on macOS." FORCE)
set(SWIFT_NATIVE_CLANG_TOOLS_PATH "${TOOLCHAIN_BOOTSTRAP_ROOT}/bin" CACHE PATH "The bootstrap toolchain supplies host tools." FORCE)
set(SWIFT_NATIVE_SWIFT_TOOLS_PATH "${TOOLCHAIN_BOOTSTRAP_ROOT}/bin" CACHE PATH "The bootstrap toolchain supplies Swift." FORCE)
set(SWIFT_PATH_TO_CMARK_SOURCE "${TOOLCHAIN_CMARK_SOURCE}" CACHE PATH "The pinned cmark source." FORCE)
set(SWIFT_PATH_TO_CMARK_BUILD "${TOOLCHAIN_BUILD_ROOT}/cmark-ios" CACHE PATH "The cmark library was built for iOS." FORCE)
set(SWIFT_PATH_TO_SWIFT_SYNTAX_SOURCE "${TOOLCHAIN_SYNTAX_SOURCE}" CACHE PATH "The parser and macro implementation use the pinned SwiftSyntax source." FORCE)
set(SWIFT_PATH_TO_STRING_PROCESSING_SOURCE "${TOOLCHAIN_REGEX_SOURCE}" CACHE PATH "The compiler retains the matching regular expression parser." FORCE)

set(SWIFT_HOST_VARIANT_SDK IOS CACHE STRING "Swift's host libraries target the iPhone SDK." FORCE)
set(SWIFT_HOST_VARIANT_ARCH arm64 CACHE STRING "Swift's host libraries use arm64." FORCE)
set(SWIFT_HOST_VARIANT iphoneos CACHE STRING "Swift's native platform variant." FORCE)
set(SWIFT_PRIMARY_VARIANT_SDK IOS CACHE STRING "Override the upstream macOS primary default." FORCE)
set(SWIFT_PRIMARY_VARIANT_ARCH arm64 CACHE STRING "The primary architecture matches the compiler host." FORCE)
set(SWIFT_SDKS IOS CACHE STRING "Only the compiler host SDK is configured." FORCE)
set(SWIFT_DARWIN_DEPLOYMENT_VERSION_IOS ${TOOLCHAIN_DEPLOYMENT_TARGET} CACHE STRING "Swift libraries match the compiler deployment floor." FORCE)
set(BOOTSTRAPPING_MODE HOSTTOOLS CACHE STRING "Use the existing macOS compiler for Swift implementation code." FORCE)
set(SWIFT_BUILD_SWIFT_SYNTAX ON CACHE BOOL "Retain the upstream parser and macro implementation." FORCE)
set(SWIFT_ENABLE_SWIFT_IN_SWIFT ON CACHE BOOL "Retain Swift implementation code in the real compiler." FORCE)
set(SWIFT_ENABLE_IMMEDIATE_EXECUTION OFF CACHE BOOL "The compiler profile emits objects without native immediate execution." FORCE)
set(SWIFT_BUILD_DYNAMIC_STDLIB OFF CACHE BOOL "The app uses existing platform runtimes." FORCE)
set(SWIFT_BUILD_STATIC_STDLIB OFF CACHE BOOL "The WASM SDK is already installed." FORCE)
set(SWIFT_BUILD_DYNAMIC_SDK_OVERLAY OFF CACHE BOOL "This profile does not rebuild SDK overlays." FORCE)
set(SWIFT_BUILD_STATIC_SDK_OVERLAY OFF CACHE BOOL "This profile does not rebuild SDK overlays." FORCE)
set(SWIFT_INCLUDE_TESTS OFF CACHE BOOL "Only the selected compiler library graph is configured." FORCE)
set(SWIFT_INCLUDE_DOCS OFF CACHE BOOL "Upstream documentation is outside this build." FORCE)
set(SWIFT_BUILD_SOURCEKIT OFF CACHE BOOL "The compiler profile does not require SourceKit." FORCE)
set(SWIFT_BUILD_REMOTE_MIRROR OFF CACHE BOOL "The compiler profile does not require a remote mirror." FORCE)
set(SWIFT_INCLUDE_APINOTES OFF CACHE BOOL "The compiler profile does not install SDK API notes." FORCE)
set(SWIFT_APPEND_VC_REV OFF CACHE BOOL "Archive inputs use manifest provenance instead of a parent Git checkout." FORCE)
