include("${TOOLCHAIN_SOURCE_DIR}/CMake/ArtifactHelpers.cmake")
set(value "A path with spaces, a quote \" and a backslash \\ plus\na second line\tand a tab")
toolchain_json_string(encoded "${value}")
string(JSON object SET "{}" value "${encoded}")
string(JSON decoded GET "${object}" value)
if(NOT decoded STREQUAL value)
  message(FATAL_ERROR "Artifact metadata changed a JSON string during serialization.")
endif()
toolchain_validate_name(_CompilerSwiftSyntax)
toolchain_validate_name(SwiftCompilerSDK)
