include("${TOOLCHAIN_SOURCE_DIR}/CMake/CacheManifest.cmake")
if(VERIFY_ONLY)
  toolchain_verify_cache("${CASE_ROOT}/receipt.json" "${CASE_ROOT}" "${EXPECTED_ID}" A.dylib B.dylib)
  return()
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef identity)
set(root "${TOOLCHAIN_TEST_ROOT}/${identity}")
file(MAKE_DIRECTORY "${root}")
file(WRITE "${root}/A.dylib" "first library\n")
file(WRITE "${root}/B.dylib" "second library\n")
toolchain_record_cache("${root}/receipt.json" "${root}" "${identity}" A.dylib B.dylib)
file(READ "${root}/receipt.json" original_manifest)

# Each failing input is checked in another CMake process because validation stops packaging immediately.
function(expect_cache expected_success expected_message requested_identity)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DTOOLCHAIN_SOURCE_DIR=${TOOLCHAIN_SOURCE_DIR}"
    "-DCASE_ROOT=${root}" "-DEXPECTED_ID=${requested_identity}" -DVERIFY_ONLY=ON
    -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(expected_success)
    if(NOT status EQUAL 0)
      message(FATAL_ERROR "A valid cache was rejected. ${output} ${error}")
    endif()
  elseif(status EQUAL 0 OR NOT error MATCHES "${expected_message}")
    message(FATAL_ERROR "Invalid cache validation returned ${status}. ${output} ${error}")
  endif()
endfunction()

expect_cache(TRUE "" "${identity}")
file(APPEND "${root}/A.dylib" "substituted\n")
expect_cache(FALSE "integrity check" "${identity}")
file(WRITE "${root}/A.dylib" "first library\n")
file(REMOVE "${root}/B.dylib")
expect_cache(FALSE "file is missing" "${identity}")
file(WRITE "${root}/B.dylib" "second library\n")
expect_cache(FALSE "identity is stale" "different-inputs")
file(REMOVE "${root}/receipt.json")
expect_cache(FALSE "manifest is missing" "${identity}")
file(WRITE "${root}/receipt.json" "${original_manifest}")
string(JSON invalid SET "${original_manifest}" files 1 path "\"A.dylib\"")
file(WRITE "${root}/receipt.json" "${invalid}")
expect_cache(FALSE "unexpected file identity" "${identity}")
file(WRITE "${root}/receipt.json" "${original_manifest}")
expect_cache(TRUE "" "${identity}")
