include("${TOOLCHAIN_SOURCE_DIR}/CMake/VerifyNoticeSource.cmake")
if(VERIFY_ONLY)
  file(READ "${CASE_ROOT}/Entry.json" entry)
  toolchain_verify_notice_source("${CASE_ROOT}/Source.cpp" "${entry}" "${CASE_ROOT}/Notice.txt")
  return()
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef identity)
set(root "${TOOLCHAIN_TEST_ROOT}/${identity}")
file(MAKE_DIRECTORY "${root}")
set(selection "/*-\n * Complete terms; retained exactly.\n *\n * * A second line.  \n */\n")
file(WRITE "${root}/Source.cpp" "// Unrelated source.\n${selection}int main();\n")
file(WRITE "${root}/Notice.txt" "Complete terms; retained exactly.\n\n* A second line.\n")
string(SHA256 checksum "${selection}")
set(entry "{\"startLine\":2,\"endLine\":6,\"upstreamTextSHA256\":\"${checksum}\"}")
file(WRITE "${root}/Entry.json" "${entry}")

# Invalid selections run separately because preparation must stop before copying notice text.
function(expect_source expected_success expected_message)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DTOOLCHAIN_SOURCE_DIR=${TOOLCHAIN_SOURCE_DIR}"
    "-DCASE_ROOT=${root}" -DVERIFY_ONLY=ON -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(expected_success)
    if(NOT status EQUAL 0)
      message(FATAL_ERROR "A valid notice source was rejected. ${output} ${error}")
    endif()
  elseif(status EQUAL 0 OR NOT error MATCHES "${expected_message}")
    message(FATAL_ERROR "An invalid notice source returned ${status}. ${output} ${error}")
  endif()
endfunction()

expect_source(TRUE "")
string(JSON invalid SET "${entry}" startLine 3)
file(WRITE "${root}/Entry.json" "${invalid}")
expect_source(FALSE "complete block comment")
string(JSON invalid SET "${entry}" endLine 5)
file(WRITE "${root}/Entry.json" "${invalid}")
expect_source(FALSE "complete block comment")
string(JSON invalid SET "${entry}" endLine 1)
file(WRITE "${root}/Entry.json" "${invalid}")
expect_source(FALSE "ordered, positive line range")
string(JSON invalid SET "${entry}" endLine 100)
file(WRITE "${root}/Entry.json" "${invalid}")
expect_source(FALSE "only comment lines")
file(WRITE "${root}/Entry.json" "${entry}")
file(WRITE "${root}/Source.cpp" "// Unrelated source.\n/*-\n * Incomplete terms.\n *\n * A second line.\n */\n")
expect_source(FALSE "upstream selection checksum")
file(WRITE "${root}/Source.cpp" "// Unrelated source.\n${selection}int main();\n")
file(WRITE "${root}/Notice.txt" "Incomplete terms.\n")
expect_source(FALSE "text differs from its upstream selection")
