include("${TOOLCHAIN_SOURCE_DIR}/CMake/VerifyNotices.cmake")
if(VERIFY_ONLY)
  toolchain_verify_notices("${CASE_ROOT}")
  return()
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef identity)
set(root "${TOOLCHAIN_TEST_ROOT}/${identity}")
file(MAKE_DIRECTORY "${root}/Native" "${root}/TargetLibraries/SDK")
file(WRITE "${root}/Native/Library.txt" "A native license.\n")
file(WRITE "${root}/TargetLibraries/SDK/LICENSE" "A target license.\n")
file(SHA256 "${root}/Native/Library.txt" native_hash)
file(SHA256 "${root}/TargetLibraries/SDK/LICENSE" target_hash)
set(native "{\"schemaVersion\":1,\"sources\":[{\"path\":\"Native/Library.txt\",\"sha256\":\"${native_hash}\"}]}")
set(target "{\"schemaVersion\":1,\"sources\":[{\"path\":\"TargetLibraries/SDK/LICENSE\",\"sha256\":\"${target_hash}\"}]}")
file(WRITE "${root}/NativeSources.json" "${native}")
file(WRITE "${root}/SDKSources.json" "${target}")

# A failed notice check runs separately because it terminates artifact verification.
function(expect_notices expected_success expected_message)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DTOOLCHAIN_SOURCE_DIR=${TOOLCHAIN_SOURCE_DIR}"
    "-DCASE_ROOT=${root}" -DVERIFY_ONLY=ON -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(expected_success)
    if(NOT status EQUAL 0)
      message(FATAL_ERROR "Valid notices were rejected. ${output} ${error}")
    endif()
  elseif(status EQUAL 0 OR NOT error MATCHES "${expected_message}")
    message(FATAL_ERROR "Invalid notices returned ${status}. ${output} ${error}")
  endif()
endfunction()

expect_notices(TRUE "")
file(APPEND "${root}/Native/Library.txt" "Changed terms.\n")
expect_notices(FALSE "content checksum")
file(WRITE "${root}/Native/Library.txt" "A native license.\n")
file(REMOVE "${root}/TargetLibraries/SDK/LICENSE")
expect_notices(FALSE "file is missing")
file(WRITE "${root}/TargetLibraries/SDK/LICENSE" "A target license.\n")
string(JSON invalid SET "${native}" sources 0 path "\"../LICENSE\"")
file(WRITE "${root}/NativeSources.json" "${invalid}")
expect_notices(FALSE "paths must be unique")
file(WRITE "${root}/NativeSources.json" "${native}")
file(REMOVE "${root}/SDKSources.json")
expect_notices(FALSE "inventory is missing")
file(WRITE "${root}/SDKSources.json" "${target}")
expect_notices(TRUE "")
