file(GLOB patches "${TOOLCHAIN_SOURCE_DIR}/Patches/*.patch")
foreach(patch IN LISTS patches)
  file(STRINGS "${patch}" lines)
  set(in_hunk FALSE)
  set(has_context FALSE)
  foreach(line IN LISTS lines)
    if(line MATCHES "^@@ " OR line MATCHES "^--- ")
      if(in_hunk AND NOT has_context)
        message(FATAL_ERROR "${patch} has a hunk without source context.")
      endif()
      set(in_hunk FALSE)
      set(has_context FALSE)
      if(line MATCHES "^@@ ")
        set(in_hunk TRUE)
      endif()
    elseif(in_hunk AND line MATCHES "^ ")
      set(has_context TRUE)
    endif()
  endforeach()
  if(in_hunk AND NOT has_context)
    message(FATAL_ERROR "${patch} has a hunk without source context.")
  endif()
endforeach()
