if(NOT DEFINED TOOLCHAIN_NATIVE_CACHE OR NOT IS_DIRECTORY "${TOOLCHAIN_NATIVE_CACHE}")
  message(FATAL_ERROR "Set TOOLCHAIN_NATIVE_CACHE to a prepared native producer cache.")
endif()
file(REAL_PATH "${TOOLCHAIN_NATIVE_CACHE}" TOOLCHAIN_NATIVE_CACHE)
set(TOOLCHAIN_SOURCE_ROOT "${TOOLCHAIN_NATIVE_CACHE}/sources")
include("${CMAKE_CURRENT_LIST_DIR}/Inputs.cmake")
file(SHA256 "${TOOLCHAIN_LOCK_FILE}" lock_digest)
string(SHA256 input_digest
  "${lock_digest}${TOOLCHAIN_PATCH_SHA256}${TOOLCHAIN_METADATA_PATCH_SHA256}${TOOLCHAIN_RESTRICTED_SWIFT_PATCH_SHA256}${TOOLCHAIN_RESTRICTED_LLVM_PATCH_SHA256}")
set(TOOLCHAIN_BUILD_ROOT "${TOOLCHAIN_NATIVE_CACHE}/build/${input_digest}")
set(TOOLCHAIN_SWIFT_BUILD "${TOOLCHAIN_BUILD_ROOT}/swift-ios")
set(TOOLCHAIN_COMPILER_LIBRARIES "${TOOLCHAIN_SWIFT_BUILD}/lib/swift/host/compiler")
if(NOT EXISTS "${TOOLCHAIN_SWIFT_BUILD}/lib/libSwiftCompilerBridge.dylib")
  message(FATAL_ERROR "Build toolchain-compiler before preparing consumer artifacts.")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/CacheManifest.cmake")
toolchain_native_identity(native_identity)
toolchain_native_files(native_files "${TOOLCHAIN_SWIFT_BUILD}")
toolchain_verify_cache("${TOOLCHAIN_SWIFT_BUILD}/NativeArtifacts.json"
  "${TOOLCHAIN_SWIFT_BUILD}" "${native_identity}" ${native_files})
file(SHA256 "${TOOLCHAIN_SWIFT_BUILD}/NativeArtifacts.json" TOOLCHAIN_NATIVE_RECEIPT_SHA256)
file(READ "${TOOLCHAIN_SWIFT_BUILD}/NativeArtifacts.json" native_manifest)
string(JSON recorded_lock GET "${native_manifest}" configurationSHA256)
string(JSON recorded_patch GET "${native_manifest}" frontendPatchSHA256)
string(JSON recorded_metadata_patch GET "${native_manifest}" filesystemMetadataPatchSHA256)
string(JSON recorded_restricted_swift_patch GET "${native_manifest}" restrictedSwiftPatchSHA256)
string(JSON recorded_restricted_llvm_patch GET "${native_manifest}" restrictedLLVMPatchSHA256)
if(NOT recorded_lock STREQUAL lock_digest OR NOT recorded_patch STREQUAL TOOLCHAIN_PATCH_SHA256
    OR NOT recorded_metadata_patch STREQUAL TOOLCHAIN_METADATA_PATCH_SHA256
    OR NOT recorded_restricted_swift_patch STREQUAL TOOLCHAIN_RESTRICTED_SWIFT_PATCH_SHA256
    OR NOT recorded_restricted_llvm_patch STREQUAL TOOLCHAIN_RESTRICTED_LLVM_PATCH_SHA256)
  message(FATAL_ERROR "The native cache provenance does not match the selected lock and patch.")
endif()
