if(NOT DEFINED TOOLCHAIN_NATIVE_CACHE OR NOT IS_DIRECTORY "${TOOLCHAIN_NATIVE_CACHE}")
  message(FATAL_ERROR "Set TOOLCHAIN_NATIVE_CACHE to a prepared native producer cache.")
endif()
file(REAL_PATH "${TOOLCHAIN_NATIVE_CACHE}" TOOLCHAIN_NATIVE_CACHE)
set(TOOLCHAIN_SOURCE_ROOT "${TOOLCHAIN_NATIVE_CACHE}/sources")
include("${CMAKE_CURRENT_LIST_DIR}/Inputs.cmake")
file(SHA256 "${TOOLCHAIN_LOCK_FILE}" lock_digest)
string(SHA256 input_digest "${lock_digest}${TOOLCHAIN_PATCH_SHA256}")
set(TOOLCHAIN_BUILD_ROOT "${TOOLCHAIN_NATIVE_CACHE}/build/${input_digest}")
set(TOOLCHAIN_SWIFT_BUILD "${TOOLCHAIN_BUILD_ROOT}/swift-ios")
set(TOOLCHAIN_COMPILER_LIBRARIES "${TOOLCHAIN_SWIFT_BUILD}/lib/swift/host/compiler")
if(NOT EXISTS "${TOOLCHAIN_SWIFT_BUILD}/lib/libSwiftCompilerBridge.dylib")
  message(FATAL_ERROR "Build toolchain-compiler before preparing consumer artifacts.")
endif()
