get_filename_component(TOOLCHAIN_REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(TOOLCHAIN_LOCK_FILE "${TOOLCHAIN_REPOSITORY_ROOT}/Toolchain.lock.json")
file(READ "${TOOLCHAIN_LOCK_FILE}" TOOLCHAIN_INPUTS)
string(JSON TOOLCHAIN_SCHEMA GET "${TOOLCHAIN_INPUTS}" schemaVersion)
string(JSON TOOLCHAIN_SWIFT_VERSION GET "${TOOLCHAIN_INPUTS}" swiftVersion)
string(JSON TOOLCHAIN_COMPILER_HOST GET "${TOOLCHAIN_INPUTS}" compilerHost)
string(JSON TOOLCHAIN_PROGRAM_TARGET GET "${TOOLCHAIN_INPUTS}" programTarget)
if(NOT TOOLCHAIN_SCHEMA EQUAL 1)
  message(FATAL_ERROR "The native recipes require toolchain input schema 1.")
endif()
if(NOT TOOLCHAIN_COMPILER_HOST MATCHES "^arm64-apple-ios([0-9]+\\.[0-9]+)$")
  message(FATAL_ERROR "The compiler host must be an arm64 iOS device target.")
endif()
set(TOOLCHAIN_DEPLOYMENT_TARGET "${CMAKE_MATCH_1}")
if(NOT TOOLCHAIN_PROGRAM_TARGET STREQUAL "wasm32-unknown-wasip1")
  message(FATAL_ERROR "The current recipes emit wasm32-unknown-wasip1 programs.")
endif()

file(SHA256 "${TOOLCHAIN_REPOSITORY_ROOT}/Patches/DisableImmediateExecution.patch"
  TOOLCHAIN_PATCH_SHA256)
string(JSON TOOLCHAIN_SOURCE_COUNT LENGTH "${TOOLCHAIN_INPUTS}" sources)
math(EXPR TOOLCHAIN_LAST_SOURCE "${TOOLCHAIN_SOURCE_COUNT} - 1")
set(TOOLCHAIN_SOURCE_NAMES "")
foreach(index RANGE ${TOOLCHAIN_LAST_SOURCE})
  string(JSON name GET "${TOOLCHAIN_INPUTS}" sources ${index} name)
  string(JSON repository GET "${TOOLCHAIN_INPUTS}" sources ${index} repository)
  string(JSON revision GET "${TOOLCHAIN_INPUTS}" sources ${index} revision)
  string(JSON checksum GET "${TOOLCHAIN_INPUTS}" sources ${index} archiveSHA256)
  string(LENGTH "${revision}" revision_length)
  string(LENGTH "${checksum}" checksum_length)
  if(NOT name MATCHES "^[a-z][a-z0-9-]*$" OR name IN_LIST TOOLCHAIN_SOURCE_NAMES
      OR NOT revision MATCHES "^[a-f0-9]+$" OR NOT revision_length EQUAL 40
      OR NOT checksum MATCHES "^[a-f0-9]+$" OR NOT checksum_length EQUAL 64)
    message(FATAL_ERROR "Source ${index} needs a unique name, full revision, and archive checksum.")
  endif()
  if(NOT repository MATCHES "^https://github.com/([A-Za-z0-9_.-]+)/([A-Za-z0-9_.-]+)\\.git$")
    message(FATAL_ERROR "Native archive preparation requires a public GitHub source URL.")
  endif()
  set(TOOLCHAIN_${name}_URL
    "https://codeload.github.com/${CMAKE_MATCH_1}/${CMAKE_MATCH_2}/tar.gz/${revision}")
  set(TOOLCHAIN_${name}_SHA256 "${checksum}")
  set(TOOLCHAIN_${name}_REVISION "${revision}")
  set(identity "${name}-${revision}")
  if(name STREQUAL "swift")
    string(APPEND identity "-${TOOLCHAIN_PATCH_SHA256}")
  endif()
  set(TOOLCHAIN_${name}_IDENTITY "${identity}")
  set(TOOLCHAIN_${name}_SOURCE "${TOOLCHAIN_SOURCE_ROOT}/${identity}")
  list(APPEND TOOLCHAIN_SOURCE_NAMES "${name}")
endforeach()

foreach(required swift llvm-project swift-cmark swift-syntax string-processing)
  if(NOT required IN_LIST TOOLCHAIN_SOURCE_NAMES)
    message(FATAL_ERROR "The native recipes require the ${required} source component.")
  endif()
endforeach()
set(TOOLCHAIN_SWIFT_SOURCE "${TOOLCHAIN_swift_SOURCE}")
set(TOOLCHAIN_LLVM_SOURCE "${TOOLCHAIN_llvm-project_SOURCE}")
set(TOOLCHAIN_CMARK_SOURCE "${TOOLCHAIN_swift-cmark_SOURCE}")
set(TOOLCHAIN_SYNTAX_SOURCE "${TOOLCHAIN_swift-syntax_SOURCE}")
set(TOOLCHAIN_REGEX_SOURCE "${TOOLCHAIN_string-processing_SOURCE}")
