# These library targets satisfy the pinned frontend and bridge link closure.
set(TOOLCHAIN_NATIVE_LIBRARIES
  lldWasm
  lldCommon
  clangTooling
  clangToolingRefactor
  clangToolingRefactoring
  clangToolingSyntax
  clangDependencyScanning
  clangFrontendTool
  clangCodeGen
  LLVMCoverage
  LLVMFrontendDriver
  clangExtractAPI
  clangInstallAPI
  LLVMTextAPIBinaryReader
  clangStaticAnalyzerFrontend
  clangStaticAnalyzerCheckers
  clangStaticAnalyzerCore
  clangCrossTU
  clangIndex
  clangFormat
  clangToolingInclusions
  clangToolingCore
  clangRewriteFrontend
  clangFrontend
  clangDriver
  LLVMWindowsDriver
  clangParse
  clangCAS
  clangSerialization
  clangSema
  clangAPINotes
  clangAnalysis
  clangASTMatchers
  clangSupport
  clangEdit
  clangAST
  LLVMFrontendHLSL
  clangRewrite
  clangLex
  clangBasic
  LLVMWebAssemblyCodeGen
  LLVMAsmPrinter
  LLVMWebAssemblyAsmParser
  LLVMWebAssemblyDisassembler
  LLVMMCDisassembler
  LLVMWebAssemblyUtils
  LLVMWebAssemblyDesc
  LLVMWebAssemblyInfo
  LLVMLTO
  LLVMExtensions
  LLVMRemoteCachingService
  LLVMRemoteNullService
  LLVMOption
  LLVMPasses
  LLVMIRPrinter
  LLVMCFGuard
  LLVMGlobalISel
  LLVMSelectionDAG
  LLVMCodeGen
  LLVMCGData
  LLVMObjCARCOpts
  LLVMMCCAS
  LLVMTarget
  LLVMCodeGenTypes
  LLVMCoroutines
  LLVMipo
  LLVMBitWriter
  LLVMFrontendOpenMP
  LLVMFrontendOffloading
  LLVMObjectYAML
  LLVMFrontendAtomic
  LLVMFrontendDirective
  LLVMScalarOpts
  LLVMAggressiveInstCombine
  LLVMInstCombine
  LLVMInstrumentation
  LLVMLinker
  LLVMHipStdPar
  LLVMVectorize
  LLVMTransformUtils
  LLVMSandboxIR
  LLVMAnalysis
  LLVMProfileData
  LLVMSymbolize
  LLVMDebugInfoGSYM
  LLVMDebugInfoDWARF
  LLVMDebugInfoPDB
  LLVMObject
  LLVMMCParser
  LLVMMC
  LLVMCASUtil
  LLVMCAS
  LLVMIRReader
  LLVMBitReader
  LLVMAsmParser
  LLVMCore
  LLVMDemangle
  LLVMRemarks
  LLVMBitstreamReader
  LLVMTextAPI
  LLVMDebugInfoCodeView
  LLVMDebugInfoMSF
  LLVMDebugInfoBTF
  LLVMDebugInfoDWARFLowLevel
  LLVMBinaryFormat
  LLVMTargetParser
  LLVMSupport
)
