include("${CMAKE_CURRENT_LIST_DIR}/ArtifactInputs.cmake")
set(TOOLCHAIN_FRAMEWORK_ROOT "${TOOLCHAIN_ARTIFACT_OUTPUT}/Frameworks/${TOOLCHAIN_SLICE}")
set(TOOLCHAIN_PACKAGE_WORK "${TOOLCHAIN_ARTIFACT_OUTPUT}/Work/${TOOLCHAIN_SLICE}")
file(MAKE_DIRECTORY "${TOOLCHAIN_FRAMEWORK_ROOT}" "${TOOLCHAIN_PACKAGE_WORK}")
if(NOT EXISTS "${TOOLCHAIN_MACRO_OUTPUT}/libSwiftInProcPluginServer.dylib")
  message(FATAL_ERROR "Run BuildMacros.cmake before packaging compiler artifacts.")
endif()
file(SHA256 "${TOOLCHAIN_REPOSITORY_ROOT}/Patches/MainActorMacroEntry.patch" macro_patch)
file(SHA256 "${TOOLCHAIN_REPOSITORY_ROOT}/Patches/BundledMacroLibraries.patch" bundled_macro_patch)
file(SHA256 "${TOOLCHAIN_REPOSITORY_ROOT}/Sources/MacroBridge/MacroEntry.cpp" adapter)
file(SHA256 "${TOOLCHAIN_REPOSITORY_ROOT}/Sources/MacroBridge/MacroEntry.h" adapter_header)
file(SHA256 "${TOOLCHAIN_REPOSITORY_ROOT}/CMake/BuildMacros.cmake" recipe)
string(SHA256 macro_identity
  "${TOOLCHAIN_NATIVE_RECEIPT_SHA256}${macro_patch}${bundled_macro_patch}${adapter}${adapter_header}${recipe}")
set(macro_files lib_CompilerSwiftLibraryPluginProvider.dylib libSwiftInProcPluginServer.dylib
  libObservationMacros.dylib libSwiftMacros.dylib)
toolchain_verify_cache("${TOOLCHAIN_MACRO_OUTPUT}/MacroArtifacts.json"
  "${TOOLCHAIN_MACRO_OUTPUT}" "${macro_identity}" ${macro_files})
set(libraries "")
foreach(input IN LISTS native_files)
  if(input MATCHES "^lib/swift/host/compiler/.*\.dylib$")
    list(APPEND libraries "${TOOLCHAIN_SWIFT_BUILD}/${input}")
  endif()
endforeach()
list(SORT libraries)
list(PREPEND libraries "${TOOLCHAIN_SWIFT_BUILD}/lib/libSwiftCompilerBridge.dylib")
foreach(name _CompilerSwiftLibraryPluginProvider SwiftInProcPluginServer ObservationMacros SwiftMacros)
  list(APPEND libraries "${TOOLCHAIN_MACRO_OUTPUT}/lib${name}.dylib")
endforeach()
set(names "")
set(changes "")
foreach(library IN LISTS libraries)
  toolchain_inspect_library("${library}")
  get_filename_component(filename "${library}" NAME)
  string(REGEX REPLACE "^lib(.*)\\.dylib$" "\\1" name "${filename}")
  toolchain_validate_name("${name}")
  if(name IN_LIST names)
    message(FATAL_ERROR "Native artifact names must be unique.")
  endif()
  list(APPEND names "${name}")
  list(APPEND changes -change "@rpath/${filename}" "@rpath/${name}.framework/${name}")
  set(framework "${TOOLCHAIN_FRAMEWORK_ROOT}/${name}.framework")
  file(MAKE_DIRECTORY "${framework}")
  file(COPY_FILE "${library}" "${framework}/${name}")
  toolchain_framework_plist("${framework}" "${name}")
endforeach()
foreach(name IN LISTS names)
  set(binary "${TOOLCHAIN_FRAMEWORK_ROOT}/${name}.framework/${name}")
  execute_process(COMMAND xcrun install_name_tool -id "@rpath/${name}.framework/${name}"
    ${changes} "${binary}" COMMAND_ERROR_IS_FATAL ANY)
endforeach()
toolchain_framework_module("${TOOLCHAIN_FRAMEWORK_ROOT}/SwiftCompilerBridge.framework"
  SwiftCompilerBridge "${TOOLCHAIN_REPOSITORY_ROOT}/Sources/CompilerBridge/SwiftCompilerBridge.h")
file(COPY_FILE
  "${TOOLCHAIN_REPOSITORY_ROOT}/Resources/SwiftCompilerBridge/PrivacyInfo.xcprivacy"
  "${TOOLCHAIN_FRAMEWORK_ROOT}/SwiftCompilerBridge.framework/PrivacyInfo.xcprivacy")
include("${CMAKE_CURRENT_LIST_DIR}/PrepareSDK.cmake")
list(APPEND names SwiftCompilerSDK)
include("${CMAKE_CURRENT_LIST_DIR}/PrepareMacroSDK.cmake")
