set(notices "${payload}/Notices")
file(MAKE_DIRECTORY "${notices}/Native")
file(COPY "${TOOLCHAIN_REPOSITORY_ROOT}/LICENSE" "${TOOLCHAIN_REPOSITORY_ROOT}/NOTICE"
  DESTINATION "${notices}")
set(native_notices
  "swift|LICENSE.txt|Swift.txt"
  "swift-syntax|LICENSE.txt|SwiftSyntax.txt"
  "swift-cmark|COPYING|Cmark.txt"
  "string-processing|LICENSE.txt|StringProcessing.txt"
  "llvm-project|llvm/LICENSE.TXT|LLVM.txt"
  "llvm-project|clang/LICENSE.TXT|Clang.txt"
  "llvm-project|lld/LICENSE.TXT|LLD.txt"
  "llvm-project|libcxx/LICENSE.TXT|LibCXX.txt"
  "llvm-project|libcxxabi/LICENSE.TXT|LibCXXABI.txt"
  "llvm-project|compiler-rt/LICENSE.TXT|CompilerRT.txt"
  "llvm-project|llvm/lib/Support/BLAKE3/LICENSE|BLAKE3.txt"
  "llvm-project|llvm/include/llvm/Support/LICENSE.TXT|LLVMSupport.txt")
set(records "[]")
set(index 0)
foreach(entry IN LISTS native_notices)
  string(REPLACE "|" ";" fields "${entry}")
  list(GET fields 0 component)
  list(GET fields 1 source_path)
  list(GET fields 2 filename)
  set(source "${TOOLCHAIN_${component}_SOURCE}/${source_path}")
  file(COPY_FILE "${source}" "${notices}/Native/${filename}")
  file(SHA256 "${source}" checksum)
  set(record "{}")
  string(JSON record SET "${record}" component "\"${component}\"")
  string(JSON record SET "${record}" revision "\"${TOOLCHAIN_${component}_REVISION}\"")
  string(JSON record SET "${record}" path "\"Native/${filename}\"")
  string(JSON record SET "${record}" sha256 "\"${checksum}\"")
  string(JSON records SET "${records}" ${index} "${record}")
  math(EXPR index "${index} + 1")
endforeach()
file(READ "${TOOLCHAIN_REPOSITORY_ROOT}/Licenses/NativeNotices.json" supplemental_notices)
string(JSON supplemental_schema GET "${supplemental_notices}" schemaVersion)
string(JSON supplemental_count LENGTH "${supplemental_notices}" sources)
if(NOT supplemental_schema EQUAL 1 OR supplemental_count LESS 1)
  message(FATAL_ERROR "Native notices need schema 1 and at least one source.")
endif()
math(EXPR supplemental_last "${supplemental_count} - 1")
foreach(number RANGE ${supplemental_last})
  string(JSON entry GET "${supplemental_notices}" sources ${number})
  string(JSON component GET "${entry}" component)
  string(JSON revision GET "${entry}" revision)
  string(JSON source_path GET "${entry}" sourcePath)
  string(JSON expected_source GET "${entry}" sourceSHA256)
  string(JSON path GET "${entry}" path)
  string(JSON expected GET "${entry}" sha256)
  if(NOT component IN_LIST TOOLCHAIN_SOURCE_NAMES
      OR NOT revision STREQUAL TOOLCHAIN_${component}_REVISION
      OR IS_ABSOLUTE "${source_path}" OR source_path MATCHES "(^|/)\\.\\.(/|$)"
      OR NOT path MATCHES "^Native/[A-Za-z0-9_-]+\\.txt$")
    message(FATAL_ERROR "A native notice must identify a pinned source and a local text file.")
  endif()
  file(SHA256 "${TOOLCHAIN_${component}_SOURCE}/${source_path}" actual_source)
  file(SHA256 "${TOOLCHAIN_REPOSITORY_ROOT}/Licenses/${path}" actual)
  if(NOT actual_source STREQUAL expected_source OR NOT actual STREQUAL expected)
    message(FATAL_ERROR "A native notice changed without updating its source identity.")
  endif()
  if(EXISTS "${notices}/${path}")
    message(FATAL_ERROR "Native notice paths must be unique.")
  endif()
  file(COPY_FILE "${TOOLCHAIN_REPOSITORY_ROOT}/Licenses/${path}" "${notices}/${path}")
  string(JSON records SET "${records}" ${index} "${entry}")
  math(EXPR index "${index} + 1")
endforeach()
file(READ "${TOOLCHAIN_REPOSITORY_ROOT}/Licenses/SDKNotices.json" sdk_notices)
string(JSON notice_sdk GET "${sdk_notices}" sdkVersion)
if(NOT notice_sdk STREQUAL sdk_version)
  message(FATAL_ERROR "The SDK notices must match the selected SDK release.")
endif()
string(JSON count LENGTH "${sdk_notices}" sources)
math(EXPR last "${count} - 1")
foreach(number RANGE ${last})
  string(JSON path GET "${sdk_notices}" sources ${number} path)
  string(JSON expected GET "${sdk_notices}" sources ${number} sha256)
  if(NOT path MATCHES "^TargetLibraries/" OR path MATCHES "(^|/)\\.\\.(/|$)")
    message(FATAL_ERROR "SDK notice paths must stay inside the notice source directory.")
  endif()
  set(source "${TOOLCHAIN_REPOSITORY_ROOT}/Licenses/${path}")
  file(SHA256 "${source}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "A pinned SDK notice changed without updating its identity.")
  endif()
  get_filename_component(parent "${notices}/${path}" DIRECTORY)
  file(MAKE_DIRECTORY "${parent}")
  file(COPY_FILE "${source}" "${notices}/${path}")
endforeach()
file(WRITE "${notices}/NativeSources.json" "{\"schemaVersion\":1,\"sources\":${records}}\n")
file(WRITE "${notices}/SDKSources.json" "${sdk_notices}")
include("${CMAKE_CURRENT_LIST_DIR}/VerifyNotices.cmake")
toolchain_verify_notices("${notices}")
