set(macro_sdk "${TOOLCHAIN_ARTIFACT_OUTPUT}/Development/MacroBuildSupport/${TOOLCHAIN_SLICE}")
file(MAKE_DIRECTORY "${macro_sdk}/Modules" "${macro_sdk}/Libraries" "${macro_sdk}/Includes")
set(module_files "")
foreach(input IN LISTS native_files)
  if(input MATCHES "\.swiftmodule$")
    list(APPEND module_files "${TOOLCHAIN_SWIFT_BUILD}/${input}")
  endif()
endforeach()
foreach(module IN LISTS module_files)
  file(COPY "${module}" DESTINATION "${macro_sdk}/Modules")
endforeach()
set(support_libraries "")
foreach(module IN LISTS TOOLCHAIN_COMPILER_SUPPORT_MODULES)
  list(APPEND support_libraries "${TOOLCHAIN_COMPILER_LIBRARIES}/lib_Compiler${module}.dylib")
endforeach()
file(COPY ${support_libraries} DESTINATION "${macro_sdk}/Libraries")
foreach(shim _SwiftSyntaxCShims _SwiftLibraryPluginProviderCShims)
  file(COPY "${TOOLCHAIN_SYNTAX_SOURCE}/Sources/${shim}/include/"
    DESTINATION "${macro_sdk}/Includes/${shim}")
endforeach()
file(COPY "${payload}/Notices" DESTINATION "${macro_sdk}")
file(WRITE "${macro_sdk}/Compatibility.json"
  "{\"schemaVersion\":1,\"swiftVersion\":\"${TOOLCHAIN_SWIFT_VERSION}\","
  "\"compilerHost\":\"${TOOLCHAIN_COMPILER_HOST}\",\"nativeReceiptSHA256\":\"${TOOLCHAIN_NATIVE_RECEIPT_SHA256}\"}\n")
