# Supplemental notices retain a complete upstream comment with only its formatting removed.
function(toolchain_verify_notice_source source entry packaged)
  string(JSON first GET "${entry}" startLine)
  string(JSON last GET "${entry}" endLine)
  string(JSON expected GET "${entry}" upstreamTextSHA256)
  if(NOT first MATCHES "^[1-9][0-9]*$" OR NOT last MATCHES "^[1-9][0-9]*$"
      OR last LESS_EQUAL first)
    message(FATAL_ERROR "A native notice needs an ordered, positive line range.")
  endif()
  file(READ "${source}" remaining)
  set(selected "")
  set(normalized "")
  set(number 1)
  while(number LESS_EQUAL last)
    if(remaining STREQUAL "")
      message(FATAL_ERROR "The native notice range extends beyond its source.")
    endif()
    string(FIND "${remaining}" "\n" newline)
    if(newline EQUAL -1)
      set(line "${remaining}")
      set(remaining "")
    else()
      math(EXPR length "${newline} + 1")
      string(SUBSTRING "${remaining}" 0 ${length} line)
      string(SUBSTRING "${remaining}" ${length} -1 remaining)
    endif()
    if(number GREATER_EQUAL first)
      string(APPEND selected "${line}")
      if(number EQUAL first)
        if(NOT line MATCHES "^/\\*[-]?[ \t]*\n$")
          message(FATAL_ERROR "The native notice range must select a complete block comment.")
        endif()
      elseif(number EQUAL last)
        if(NOT line MATCHES "^[ \t]*\\*/[ \t]*\n?$")
          message(FATAL_ERROR "The native notice range must select a complete block comment.")
        endif()
      else()
        if(NOT line MATCHES "^[ \t]*\\*([^/]|$)")
          message(FATAL_ERROR "The native notice range must contain only comment lines.")
        endif()
        string(REGEX MATCH "^[ \t]*\\* ?" prefix "${line}")
        string(LENGTH "${prefix}" prefix_length)
        string(SUBSTRING "${line}" ${prefix_length} -1 text)
        string(REGEX REPLACE "\n$" "" text "${text}")
        string(REGEX REPLACE "[ \t]+$" "" text "${text}")
        string(APPEND normalized "${text}\n")
      endif()
    endif()
    math(EXPR number "${number} + 1")
  endwhile()
  string(SHA256 actual "${selected}")
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "The native notice upstream selection checksum differs.")
  endif()
  string(STRIP "${normalized}" normalized)
  string(APPEND normalized "\n")
  file(READ "${packaged}" actual_text)
  if(NOT actual_text STREQUAL normalized)
    message(FATAL_ERROR "The native notice text differs from its upstream selection.")
  endif()
endfunction()
