include("${CMAKE_CURRENT_LIST_DIR}/ArtifactHelpers.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/VerifyNativeProfile.cmake")
if(NOT EXISTS "${TOOLCHAIN_ARTIFACT_OUTPUT}/ArtifactManifest.json")
  message(FATAL_ERROR "Set TOOLCHAIN_ARTIFACT_OUTPUT to the prepared consumer artifact directory.")
endif()
file(READ "${TOOLCHAIN_ARTIFACT_OUTPUT}/ArtifactManifest.json" manifest)
string(JSON schema GET "${manifest}" schemaVersion)
string(JSON abi GET "${manifest}" bridgeABI)
string(JSON host GET "${manifest}" compilerHost)
if(NOT schema EQUAL 2 OR NOT abi EQUAL 1 OR NOT host MATCHES "^arm64-apple-ios([0-9]+\\.[0-9]+)$")
  message(FATAL_ERROR "The artifact schema, ABI, or host is incompatible.")
endif()
set(TOOLCHAIN_DEPLOYMENT_TARGET "${CMAKE_MATCH_1}")
string(JSON count LENGTH "${manifest}" artifacts)
if(count LESS 1)
  message(FATAL_ERROR "The manifest contains no artifacts.")
endif()
math(EXPR last "${count} - 1")
set(names "")
foreach(index RANGE ${last})
  string(JSON name GET "${manifest}" artifacts ${index} name)
  toolchain_validate_name("${name}")
  if(name IN_LIST names)
    message(FATAL_ERROR "The artifact manifest repeats a framework name.")
  endif()
  list(APPEND names "${name}")
endforeach()
set(verification "${TOOLCHAIN_ARTIFACT_OUTPUT}/Verification")
file(MAKE_DIRECTORY "${verification}")
foreach(index RANGE ${last})
  string(JSON name GET "${manifest}" artifacts ${index} name)
  string(JSON archive GET "${manifest}" artifacts ${index} archive)
  string(JSON expected GET "${manifest}" artifacts ${index} checksum)
  string(JSON expected_bytes GET "${manifest}" artifacts ${index} archiveBytes)
  if(NOT archive STREQUAL "${name}.zip")
    message(FATAL_ERROR "The archive must be a matching ZIP basename.")
  endif()
  set(archive "${TOOLCHAIN_ARTIFACT_OUTPUT}/Archives/${archive}")
  file(SHA256 "${archive}" actual)
  file(SIZE "${archive}" actual_bytes)
  if(NOT actual STREQUAL expected OR NOT actual_bytes EQUAL expected_bytes)
    message(FATAL_ERROR "Archive integrity failed for ${name}.")
  endif()
  set(extracted "${verification}/${name}")
  file(REMOVE_RECURSE "${extracted}")
  file(MAKE_DIRECTORY "${extracted}")
  file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${extracted}")
  toolchain_inspect_xcframework("${extracted}/${name}.xcframework" "${name}")
  string(JSON slice_count LENGTH "${manifest}" artifacts ${index} slices)
  if(NOT slice_count EQUAL 2)
    message(FATAL_ERROR "Each artifact must record device and simulator slices.")
  endif()
  set(seen_slices "")
  foreach(slice_index RANGE 1)
    string(JSON slice GET "${manifest}" artifacts ${index} slices ${slice_index} identifier)
    string(JSON slice_host GET "${manifest}" artifacts ${index} slices ${slice_index} compilerHost)
    if(slice IN_LIST seen_slices)
      message(FATAL_ERROR "The artifact repeats a platform slice.")
    endif()
    list(APPEND seen_slices "${slice}")
    if(slice STREQUAL "ios-arm64")
      set(TOOLCHAIN_MACHO_PLATFORM IOS)
      set(expected_host "${host}")
    elseif(slice STREQUAL "ios-arm64-simulator")
      set(TOOLCHAIN_MACHO_PLATFORM IOSSIMULATOR)
      set(expected_host "${host}-simulator")
    else()
      message(FATAL_ERROR "The artifact contains an unsupported platform slice.")
    endif()
    if(NOT slice_host STREQUAL expected_host)
      message(FATAL_ERROR "The platform slice has an incompatible compiler host.")
    endif()
    set(framework "${extracted}/${name}.xcframework/${slice}/${name}.framework")
    set(binary "${framework}/${name}")
    if(name STREQUAL "SwiftCompilerBridge")
      file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/../Resources/SwiftCompilerBridge/PrivacyInfo.xcprivacy"
        expected_privacy)
      file(SHA256 "${framework}/PrivacyInfo.xcprivacy" actual_privacy)
      if(NOT actual_privacy STREQUAL expected_privacy)
        message(FATAL_ERROR "The compiler privacy declaration changed during packaging.")
      endif()
    endif()
    toolchain_inspect_library("${binary}")
    toolchain_verify_native_profile("${binary}")
    string(JSON expected GET "${manifest}" artifacts ${index} slices ${slice_index} binaryChecksum)
    string(JSON expected_bytes GET "${manifest}" artifacts ${index} slices ${slice_index} binaryBytes)
    file(SHA256 "${binary}" actual)
    file(SIZE "${binary}" actual_bytes)
    if(NOT actual STREQUAL expected OR NOT actual_bytes EQUAL expected_bytes)
      message(FATAL_ERROR "Executable integrity failed for ${name}.")
    endif()
    execute_process(COMMAND xcrun otool -D "${binary}" OUTPUT_VARIABLE identity
      COMMAND_ERROR_IS_FATAL ANY)
    string(FIND "${identity}" "@rpath/${name}.framework/${name}" identity_offset)
    if(identity_offset LESS 0)
      message(FATAL_ERROR "The framework install name is invalid for ${name}.")
    endif()
    execute_process(COMMAND xcrun otool -L "${binary}" OUTPUT_VARIABLE dependency_text
      COMMAND_ERROR_IS_FATAL ANY)
    string(REPLACE "\n" ";" dependencies "${dependency_text}")
    list(REMOVE_AT dependencies 0)
    foreach(line IN LISTS dependencies)
      string(STRIP "${line}" line)
      if(line STREQUAL "")
        continue()
      endif()
      string(REGEX REPLACE " \\(.*$" "" dependency "${line}")
      if(dependency MATCHES "^@rpath/([A-Za-z_][A-Za-z0-9_]*)\\.framework/([A-Za-z_][A-Za-z0-9_]*)$")
        if(NOT CMAKE_MATCH_1 STREQUAL CMAKE_MATCH_2 OR NOT CMAKE_MATCH_1 IN_LIST names)
          message(FATAL_ERROR "A native framework dependency is missing from the manifest.")
        endif()
      elseif(NOT dependency MATCHES "^(/usr/lib/|/System/Library/Frameworks/)")
        message(FATAL_ERROR "A native dependency has an unsupported install path.")
      endif()
    endforeach()
  endforeach()
endforeach()
foreach(slice ios-arm64 ios-arm64-simulator)
  set(sdk "${verification}/SwiftCompilerSDK/SwiftCompilerSDK.xcframework/${slice}/SwiftCompilerSDK.framework/Payload")
  include("${CMAKE_CURRENT_LIST_DIR}/VerifyNotices.cmake")
  toolchain_verify_notices("${sdk}/Notices")
  file(READ "${sdk}/Materialization.json" materialization)
  string(JSON module_schema GET "${materialization}" schemaVersion)
  if(module_schema EQUAL 2)
    string(JSON module_encoding GET "${materialization}" encoding)
    if(NOT module_encoding STREQUAL "lzfse")
      message(FATAL_ERROR "The SDK module encoding is unsupported.")
    endif()
    include("${CMAKE_CURRENT_LIST_DIR}/ModuleCodec.cmake")
    toolchain_prepare_module_codec(module_codec)
  elseif(NOT module_schema EQUAL 1)
    message(FATAL_ERROR "The SDK module schema is unsupported.")
  endif()
  string(JSON module_count LENGTH "${materialization}" modules)
  math(EXPR last_module "${module_count} - 1")
  foreach(index RANGE ${last_module})
    string(JSON path GET "${materialization}" modules ${index} path)
    string(JSON encoded GET "${materialization}" modules ${index} encodedPath)
    string(JSON expected GET "${materialization}" modules ${index} sha256)
    if(IS_ABSOLUTE "${path}" OR IS_ABSOLUTE "${encoded}" OR path MATCHES "(^|/)\\.\\.(/|$)"
        OR encoded MATCHES "(^|/)\\.\\.(/|$)")
      message(FATAL_ERROR "SDK module records must remain within their payload.")
    endif()
    set(decoded "${verification}/decoded-module")
    if(module_schema EQUAL 2)
      string(JSON decoded_bytes GET "${materialization}" modules ${index} decodedByteCount)
      execute_process(COMMAND "${module_codec}" module-codec decompress "${sdk}/${encoded}" "${decoded}"
        --decoded-bytes "${decoded_bytes}" COMMAND_ERROR_IS_FATAL ANY)
    else()
      execute_process(COMMAND /usr/bin/base64 --decode -i "${sdk}/${encoded}" -o "${decoded}"
        COMMAND_ERROR_IS_FATAL ANY)
    endif()
    file(SHA256 "${decoded}" actual)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "A serialized Swift module changed during packaging.")
    endif()
    file(REMOVE "${decoded}")
  endforeach()
endforeach()
string(JSON support_archive GET "${manifest}" macroBuildSupport archive)
string(JSON support_hash GET "${manifest}" macroBuildSupport checksum)
if(NOT support_archive STREQUAL "MacroBuildSupport.zip")
  message(FATAL_ERROR "The macro build support archive has an invalid path.")
endif()
file(SHA256 "${TOOLCHAIN_ARTIFACT_OUTPUT}/Archives/${support_archive}" actual_hash)
file(SIZE "${TOOLCHAIN_ARTIFACT_OUTPUT}/Archives/${support_archive}" actual_bytes)
string(JSON support_bytes GET "${manifest}" macroBuildSupport archiveBytes)
if(NOT support_hash STREQUAL actual_hash OR NOT support_bytes EQUAL actual_bytes)
  message(FATAL_ERROR "The macro build support archive failed its integrity check.")
endif()
set(support_root "${verification}/Development")
file(REMOVE_RECURSE "${support_root}")
file(ARCHIVE_EXTRACT INPUT "${TOOLCHAIN_ARTIFACT_OUTPUT}/Archives/${support_archive}"
  DESTINATION "${support_root}")
string(JSON swift_version GET "${manifest}" inputs swiftVersion)
foreach(slice ios-arm64 ios-arm64-simulator)
  set(support "${support_root}/MacroBuildSupport/${slice}")
  file(READ "${support}/Compatibility.json" compatibility)
  string(JSON support_host GET "${compatibility}" compilerHost)
  string(JSON support_swift GET "${compatibility}" swiftVersion)
  string(JSON support_schema GET "${compatibility}" schemaVersion)
  set(expected_host "${host}")
  set(TOOLCHAIN_MACHO_PLATFORM IOS)
  if(slice STREQUAL "ios-arm64-simulator")
    string(APPEND expected_host "-simulator")
    set(TOOLCHAIN_MACHO_PLATFORM IOSSIMULATOR)
  endif()
  if(NOT support_schema EQUAL 1 OR NOT support_host STREQUAL expected_host
      OR NOT support_swift STREQUAL swift_version)
    message(FATAL_ERROR "Macro support compatibility metadata targets another native environment.")
  endif()
  include("${CMAKE_CURRENT_LIST_DIR}/CompilerSupportModules.cmake")
  foreach(module IN LISTS TOOLCHAIN_COMPILER_SUPPORT_MODULES)
    if(NOT EXISTS "${support}/Modules/${module}.swiftmodule")
      message(FATAL_ERROR "Macro support is missing a serialized compiler module.")
    endif()
    toolchain_inspect_library("${support}/Libraries/lib_Compiler${module}.dylib")
  endforeach()
endforeach()
message(STATUS "Verified ${count} archives, their native dependency closure, and ${module_count} SDK modules.")
