# Release verification checks the copied notice files against both packaged source inventories.
function(toolchain_verify_notices root)
  file(REAL_PATH "${root}" canonical_root)
  set(seen "")
  foreach(manifest NativeSources.json SDKSources.json)
    if(NOT EXISTS "${root}/${manifest}")
      message(FATAL_ERROR "A bundled notice inventory is missing.")
    endif()
    file(READ "${root}/${manifest}" data)
    string(JSON schema GET "${data}" schemaVersion)
    string(JSON count LENGTH "${data}" sources)
    if(NOT schema EQUAL 1 OR count LESS 1)
      message(FATAL_ERROR "A notice inventory needs schema 1 and at least one source.")
    endif()
    math(EXPR last "${count} - 1")
    foreach(index RANGE ${last})
      string(JSON path GET "${data}" sources ${index} path)
      string(JSON expected GET "${data}" sources ${index} sha256)
      if(NOT path MATCHES "^(Native|TargetLibraries)/[A-Za-z0-9_./-]+$"
          OR path MATCHES "(^|/)\\.\\.?(/|$)" OR path IN_LIST seen
          OR IS_SYMLINK "${root}/${path}")
        message(FATAL_ERROR "Bundled notice paths must be unique regular files inside their inventory.")
      endif()
      list(APPEND seen "${path}")
      if(NOT EXISTS "${root}/${path}")
        message(FATAL_ERROR "A bundled notice file is missing.")
      endif()
      file(REAL_PATH "${root}/${path}" canonical_notice)
      cmake_path(IS_PREFIX canonical_root "${canonical_notice}" NORMALIZE contained)
      if(NOT contained)
        message(FATAL_ERROR "A bundled notice resolves outside its inventory directory.")
      endif()
      file(SHA256 "${canonical_notice}" actual)
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "A bundled notice failed its content checksum.")
      endif()
    endforeach()
  endforeach()
endfunction()
