include("${CMAKE_CURRENT_LIST_DIR}/ArtifactHelpers.cmake")
if(NOT EXISTS "${TOOLCHAIN_ARTIFACT_OUTPUT}/ArtifactManifest.json")
  message(FATAL_ERROR "Set TOOLCHAIN_ARTIFACT_OUTPUT to the prepared consumer artifact directory.")
endif()
file(READ "${TOOLCHAIN_ARTIFACT_OUTPUT}/ArtifactManifest.json" manifest)
string(JSON schema GET "${manifest}" schemaVersion)
string(JSON abi GET "${manifest}" bridgeABI)
string(JSON host GET "${manifest}" compilerHost)
if(NOT schema EQUAL 1 OR NOT abi EQUAL 1 OR NOT host MATCHES "^arm64-apple-ios([0-9]+\\.[0-9]+)$")
  message(FATAL_ERROR "The artifact schema, ABI, or host is incompatible.")
endif()
set(TOOLCHAIN_DEPLOYMENT_TARGET "${CMAKE_MATCH_1}")
string(JSON count LENGTH "${manifest}" artifacts)
if(count LESS 1)
  message(FATAL_ERROR "The manifest contains no artifacts.")
endif()
math(EXPR last "${count} - 1")
set(names "")
foreach(index RANGE ${last})
  string(JSON name GET "${manifest}" artifacts ${index} name)
  toolchain_validate_name("${name}")
  if(name IN_LIST names)
    message(FATAL_ERROR "The artifact manifest repeats a framework name.")
  endif()
  list(APPEND names "${name}")
endforeach()
set(verification "${TOOLCHAIN_ARTIFACT_OUTPUT}/Verification")
file(MAKE_DIRECTORY "${verification}")
foreach(index RANGE ${last})
  string(JSON name GET "${manifest}" artifacts ${index} name)
  string(JSON archive GET "${manifest}" artifacts ${index} archive)
  string(JSON expected GET "${manifest}" artifacts ${index} checksum)
  string(JSON expected_bytes GET "${manifest}" artifacts ${index} archiveBytes)
  if(NOT archive STREQUAL "${name}.zip")
    message(FATAL_ERROR "The archive must be a matching ZIP basename.")
  endif()
  set(archive "${TOOLCHAIN_ARTIFACT_OUTPUT}/Archives/${archive}")
  file(SHA256 "${archive}" actual)
  file(SIZE "${archive}" actual_bytes)
  if(NOT actual STREQUAL expected OR NOT actual_bytes EQUAL expected_bytes)
    message(FATAL_ERROR "Archive integrity failed for ${name}.")
  endif()
  set(extracted "${verification}/${name}")
  file(REMOVE_RECURSE "${extracted}")
  file(MAKE_DIRECTORY "${extracted}")
  file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${extracted}")
  set(framework "${extracted}/${name}.xcframework/ios-arm64/${name}.framework")
  set(binary "${framework}/${name}")
  toolchain_inspect_library("${binary}")
  string(JSON expected GET "${manifest}" artifacts ${index} binaryChecksum)
  string(JSON expected_bytes GET "${manifest}" artifacts ${index} binaryBytes)
  file(SHA256 "${binary}" actual)
  file(SIZE "${binary}" actual_bytes)
  if(NOT actual STREQUAL expected OR NOT actual_bytes EQUAL expected_bytes)
    message(FATAL_ERROR "Executable integrity failed for ${name}.")
  endif()
  execute_process(COMMAND xcrun otool -D "${binary}" OUTPUT_VARIABLE identity
    COMMAND_ERROR_IS_FATAL ANY)
  string(FIND "${identity}" "@rpath/${name}.framework/${name}" identity_offset)
  if(identity_offset LESS 0)
    message(FATAL_ERROR "The framework install name is invalid for ${name}.")
  endif()
  execute_process(COMMAND xcrun otool -L "${binary}" OUTPUT_VARIABLE dependency_text
    COMMAND_ERROR_IS_FATAL ANY)
  string(REPLACE "\n" ";" dependencies "${dependency_text}")
  list(REMOVE_AT dependencies 0)
  foreach(line IN LISTS dependencies)
    string(STRIP "${line}" line)
    if(line STREQUAL "")
      continue()
    endif()
    string(REGEX REPLACE " \\(.*$" "" dependency "${line}")
    if(dependency MATCHES "^@rpath/([A-Za-z_][A-Za-z0-9_]*)\\.framework/([A-Za-z_][A-Za-z0-9_]*)$")
      if(NOT CMAKE_MATCH_1 STREQUAL CMAKE_MATCH_2 OR NOT CMAKE_MATCH_1 IN_LIST names)
        message(FATAL_ERROR "A native framework dependency is missing from the manifest.")
      endif()
    elseif(NOT dependency MATCHES "^(/usr/lib/|/System/Library/Frameworks/)")
      message(FATAL_ERROR "A native dependency has an unsupported install path.")
    endif()
  endforeach()
endforeach()
set(sdk "${verification}/SwiftCompilerSDK/SwiftCompilerSDK.xcframework/ios-arm64/SwiftCompilerSDK.framework/Payload")
file(READ "${sdk}/Materialization.json" materialization)
string(JSON module_count LENGTH "${materialization}" modules)
math(EXPR last_module "${module_count} - 1")
foreach(index RANGE ${last_module})
  string(JSON path GET "${materialization}" modules ${index} path)
  string(JSON encoded GET "${materialization}" modules ${index} encodedPath)
  string(JSON expected GET "${materialization}" modules ${index} sha256)
  if(IS_ABSOLUTE "${path}" OR IS_ABSOLUTE "${encoded}" OR path MATCHES "(^|/)\\.\\.(/|$)"
      OR encoded MATCHES "(^|/)\\.\\.(/|$)")
    message(FATAL_ERROR "SDK module records must remain within their payload.")
  endif()
  set(decoded "${verification}/decoded-module")
  execute_process(COMMAND /usr/bin/base64 --decode -i "${sdk}/${encoded}" -o "${decoded}"
    COMMAND_ERROR_IS_FATAL ANY)
  file(SHA256 "${decoded}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "A serialized Swift module changed during packaging.")
  endif()
endforeach()
file(REMOVE "${verification}/decoded-module")
string(JSON support_archive GET "${manifest}" macroBuildSupport archive)
string(JSON support_hash GET "${manifest}" macroBuildSupport checksum)
if(NOT support_archive STREQUAL "MacroBuildSupport.zip")
  message(FATAL_ERROR "The macro build support archive has an invalid path.")
endif()
file(SHA256 "${TOOLCHAIN_ARTIFACT_OUTPUT}/Archives/${support_archive}" actual_hash)
if(NOT support_hash STREQUAL actual_hash)
  message(FATAL_ERROR "The macro build support archive failed its integrity check.")
endif()
message(STATUS "Verified ${count} archives, their native dependency closure, and ${module_count} SDK modules.")
